// <auto-generated />
using System;
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231027063123_notification")]
    partial class notification
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.DataModels.ClinicalDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasMaxLength(1024)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("QuestionId");

                    b.ToTable("clinicalDetail", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalEnhancement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsQuestionMandatory")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isQuestionMandatory");

                    b.Property<byte>("LevelOfQuestion")
                        .HasColumnType("tinyint")
                        .HasColumnName("level_of_question");

                    b.Property<string>("Options")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("options");

                    b.Property<long?>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("question");

                    b.Property<byte>("TypeOfQuestion")
                        .HasColumnType("tinyint")
                        .HasColumnName("type_of_question");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("clinicalEnhancement", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4875), new TimeSpan(0, 0, 0, 0, 0)),
                            IsQuestionMandatory = true,
                            LevelOfQuestion = (byte)1,
                            Options = "Yes,No",
                            Question = "Do you have any existing medical conditions or chronic illnesses?",
                            TypeOfQuestion = (byte)3,
                            UpdatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4876), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2L,
                            CreatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4883), new TimeSpan(0, 0, 0, 0, 0)),
                            IsQuestionMandatory = false,
                            LevelOfQuestion = (byte)1,
                            Question = "Have you ever been hospitalized for any reason?",
                            TypeOfQuestion = (byte)1,
                            UpdatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4884), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3L,
                            CreatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4885), new TimeSpan(0, 0, 0, 0, 0)),
                            IsQuestionMandatory = false,
                            LevelOfQuestion = (byte)1,
                            Options = "Blood Pressure,Indigestion,Skin Problem,Headache,Isomania",
                            Question = "What particular issues you are facing right now?",
                            TypeOfQuestion = (byte)2,
                            UpdatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4886), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4L,
                            CreatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4887), new TimeSpan(0, 0, 0, 0, 0)),
                            IsQuestionMandatory = true,
                            LevelOfQuestion = (byte)1,
                            Options = "Child,Teenager,Adult,Senior Citizen",
                            Question = "What is your age group?",
                            TypeOfQuestion = (byte)4,
                            UpdatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4887), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5L,
                            CreatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4889), new TimeSpan(0, 0, 0, 0, 0)),
                            IsQuestionMandatory = false,
                            LevelOfQuestion = (byte)1,
                            Question = "Have you ever been diagnosed with mental health conditions, such as depression or anxiety?",
                            TypeOfQuestion = (byte)1,
                            UpdatedOn = new DateTimeOffset(new DateTime(2023, 10, 27, 6, 31, 23, 102, DateTimeKind.Unspecified).AddTicks(4889), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalEnhancementAnswer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<long>("QuestionId")
                        .HasColumnType("bigint")
                        .HasColumnName("question_id");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("QuestionId");

                    b.ToTable("clinicalEnhancementAnswer", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalProcess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deadline");

                    b.Property<DateTimeOffset?>("ExpectedDate")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expected_date");

                    b.Property<string>("ExternalLink")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("external_link");

                    b.Property<byte>("NextStep")
                        .HasColumnType("tinyint")
                        .HasColumnName("next_step");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NextStep");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("clinicalProcess", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalProcessStatus", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("clinicalProcessStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "Initial"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "Clinical Path"
                        },
                        new
                        {
                            Id = (byte)3,
                            Title = "Prescribe Test"
                        },
                        new
                        {
                            Id = (byte)4,
                            Title = "Collect Sample"
                        },
                        new
                        {
                            Id = (byte)5,
                            Title = "Ship Sample"
                        },
                        new
                        {
                            Id = (byte)6,
                            Title = "Receive Sample"
                        },
                        new
                        {
                            Id = (byte)7,
                            Title = "Sample Analysis"
                        },
                        new
                        {
                            Id = (byte)8,
                            Title = "Send Lab Results"
                        },
                        new
                        {
                            Id = (byte)9,
                            Title = "Publish Report"
                        },
                        new
                        {
                            Id = (byte)10,
                            Title = "Complete"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalProcessTest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ClinicalProcessId")
                        .HasColumnType("bigint")
                        .HasColumnName("clinical_process_id");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<long>("TestId")
                        .HasColumnType("bigint")
                        .HasColumnName("test_id");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalProcessId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id");

                    b.HasIndex("TestId");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("clinicalProcessTest", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.HasIndex("Question")
                        .IsUnique();

                    b.ToTable("clinicalQuestion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Question = "Do you have any existing medical conditions or chronic illnesses?"
                        },
                        new
                        {
                            Id = 2,
                            Question = "Have you ever been hospitalized for any reason? If yes, please provide details"
                        },
                        new
                        {
                            Id = 3,
                            Question = "Are you currently taking any medications, either prescription or over-the-counter?"
                        },
                        new
                        {
                            Id = 4,
                            Question = "Do you have any known allergies to medications, foods, or other substances?"
                        },
                        new
                        {
                            Id = 5,
                            Question = "Have you ever been diagnosed with mental health conditions, such as depression or anxiety?"
                        },
                        new
                        {
                            Id = 6,
                            Question = "Have you ever had any surgeries or major medical procedures in the past?"
                        },
                        new
                        {
                            Id = 7,
                            Question = "Do you smoke or have a history of smoking? If yes, how many cigarettes per day and for how long ? "
                        },
                        new
                        {
                            Id = 8,
                            Question = "Do you consume alcohol? If yes, how often and how much?"
                        },
                        new
                        {
                            Id = 9,
                            Question = "Are you physically active, and do you exercise regularly ?"
                        },
                        new
                        {
                            Id = 10,
                            Question = "Have you experienced any recent changes in weight, appetite, or energy levels ?"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.FAQ", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("answer");

                    b.Property<byte>("ForWhom")
                        .HasColumnType("tinyint")
                        .HasColumnName("for_whom");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(124)
                        .HasColumnType("varchar(124)")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("PK_FAQ_Id");

                    b.HasIndex("ForWhom");

                    b.HasIndex("Question")
                        .IsUnique();

                    b.ToTable("faq", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "Genetic testing offers valuable insights into patients' genetic makeup, aiding in the identification of potential disease risks, hereditary conditions, and treatment responses. It enables personalized medical decisions and empowers patients to make informed choices about their health. Interpreting genetic test results involves analyzing genetic variants for their clinical significance and relevance to patients' health. Our comprehensive genetic tests provide detailed information about genetic variants, enabling tailored healthcare plans. Please note: While genetic testing provides crucial information, clinical expertise is essential for translating these insights into effective patient care.",
                            ForWhom = (byte)1,
                            Question = "What are the key benefits of genetic testing for my patients?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "Interpreting genetic test results involves analyzing genetic variants for their clinical significance and relevance to patients' health. We provide clear reports outlining identified variants and their potential implications. However, it's crucial to consider these results within the broader clinical context. Genetic counselors and specialists can assist in understanding the implications and guiding treatment decisions. Please Note: Genetic test results provide valuable data, but they should be integrated with clinical judgment and expert advice.",
                            ForWhom = (byte)1,
                            Question = "How do I interpret genetic test results for my patients?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Yes, we offer genetic tests designed to assess cancer risk by identifying mutations associated with various types of cancer. These tests analyze genes linked to hereditary cancer syndromes. Detected mutations can inform early detection strategies and guide preventative measures. However, it's important to remember that genetic risk is just one factor, and regular screenings and consultations with oncologists are crucial. Please note: Genetic tests provide risk information, but comprehensive cancer care involves collaboration with specialists.",
                            ForWhom = (byte)1,
                            Question = "Are there specific genetic tests for cancer risk assessment?"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Pharmacogenetic testing examines genetic variations influencing how patients metabolize medications. This information helps tailor medication selection and dosage for improved efficacy and reduced risk of adverse reactions. However, while these insights are valuable, they should be used alongside clinical judgment and patient history. Pharmacogenetic testing enhances personalized medicine, but ongoing monitoring and adjustments are vital. Please Note: Genetic testing informs medication decisions, but individual responses can vary and require medical expertise.",
                            ForWhom = (byte)1,
                            Question = "How can pharmacogenetic testing improve patient medication management?"
                        },
                        new
                        {
                            Id = 5,
                            Answer = "Genetic testing provides insights into your unique genetic makeup, helping identify potential risks for certain health conditions and guiding personalized healthcare decisions. Understanding your genetic predispositions empowers you to adopt preventive measures and make informed lifestyle choices. However, it's important to remember that genetics is just one factor influencing your health. Genetic testing offers valuable information, but medical advice from healthcare professionals remains essential for holistic well-being.",
                            ForWhom = (byte)2,
                            Question = "How can genetic testing benefit my health?"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "Yes, pharmacogenetic testing examines genetic variants affecting how your body processes medications. This insight can help healthcare providers tailor medication choices and dosages for better treatment outcomes and reduced risks of adverse reactions. Nevertheless, while genetic testing offers valuable guidance, individual responses can vary. Genetic insights complement medical care, but ongoing communication with healthcare professionals is crucial for optimal medication management.",
                            ForWhom = (byte)2,
                            Question = "Can genetic testing predict my response to medications?"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "Genetic testing can indicate certain genetic predispositions to diseases, but it's important to note that genetics is just one part of the equation. Lifestyle factors, family history, and other environmental influences also play significant roles. Understanding your genetic risk empowers you to take proactive steps toward prevention, but it's essential to consult healthcare providers for comprehensive health assessments and personalized guidance.",
                            ForWhom = (byte)2,
                            Question = "Will genetic testing tell me if I'm likely to develop a certain disease?"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "Yes, genetic testing can help diagnose certain rare genetic conditions by identifying specific genetic mutations associated with those conditions. However, a confirmed diagnosis often involves a combination of genetic testing, clinical evaluations, and medical history analysis. Genetic testing provides valuable information, but the interpretation of results and subsequent medical decisions should be discussed with healthcare professionals who can guide you through the process.",
                            ForWhom = (byte)2,
                            Question = "Can genetic testing diagnose rare conditions I might have?"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "Our lab provides a diverse range of genetic tests, including panels for hereditary conditions, pharmacogenetics, and disease risk assessment. We offer comprehensive sequencing and analysis of relevant genes, empowering healthcare providers with valuable patient insights. Please note that while our tests provide essential genetic information, clinical expertise is vital for translating these findings into effective patient care.",
                            ForWhom = (byte)3,
                            Question = "What types of genetic tests does our lab offer?"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "We prioritize accuracy through stringent quality control measures, employing advanced sequencing technologies and validated protocols. Our lab's team of skilled professionals ensures that tests are conducted with precision and attention to detail. While we strive for accurate results, the interpretation and clinical application of genetic findings require the expertise of healthcare professionals. Genetic testing offers valuable insights, but the collaboration with medical experts is essential for patient care.",
                            ForWhom = (byte)3,
                            Question = "How can our lab ensure the accuracy of genetic test results?"
                        },
                        new
                        {
                            Id = 11,
                            Answer = "While our lab provides comprehensive genetic testing and reporting, the interpretation of results within a clinical context is best undertaken by healthcare providers. We offer clear and detailed reports outlining identified variants, but these findings should be correlated with patients' medical history and clinical presentation. Genetic testing is a valuable tool, but medical expertise is essential for translating genetic insights into actionable care decisions.",
                            ForWhom = (byte)3,
                            Question = "Can our lab assist in the interpretation of genetic test results?"
                        },
                        new
                        {
                            Id = 12,
                            Answer = "Our lab plays a pivotal role in personalized medicine by providing genetic data that can inform tailored healthcare strategies. Genetic insights offer valuable information about disease risks, treatment responses, and medication management. However, it's important to remember that genetics is just one aspect of patient care. Genetic testing contributes to personalized medicine, but its successful implementation requires collaborative efforts between lab professionals and healthcare providers.",
                            ForWhom = (byte)3,
                            Question = "What role does our lab play in advancing personalized medicine?"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.Gender", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("PK_Gender_Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("gender", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "Male"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "Female"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<bool>("HasRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("has_read");

                    b.Property<bool>("IsTempDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_temp_deleted");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("notification_message");

                    b.Property<long>("SendTo")
                        .HasColumnType("bigint")
                        .HasColumnName("send_to");

                    b.Property<long>("SentBy")
                        .HasColumnType("bigint")
                        .HasColumnName("sent_by");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("SendTo");

                    b.HasIndex("SentBy");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.RequestMoreInfoQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Answer")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("answer");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<long>("PatientId")
                        .HasColumnType("bigint")
                        .HasColumnName("patient_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("question");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("requestMoreInfoQuestion");
                });

            modelBuilder.Entity("Entities.DataModels.SwipeActionSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("SwipeLeftAction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Delete")
                        .HasColumnName("swipe_left_action");

                    b.Property<string>("SwipeRightAction")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Read")
                        .HasColumnName("swipe_right_action");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_Id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("swipeActionSetting", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.TestDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)")
                        .HasColumnName("description");

                    b.Property<byte>("Duration")
                        .HasColumnType("tinyint")
                        .HasColumnName("duration");

                    b.Property<double>("Price")
                        .HasColumnType("float")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("testDetail", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Abbreviation = "WES",
                            Description = "Detailed description of the sequencing method & relevant gene coverage. Report of rare causative variants described in the literature with pathogenetic significance. Report of rare variants with frequency in the genral population (Minor Allele Frequency - MAF) < 1%. Clear variants of the results identified on the basis of international guidlines on 'best practices'. Please Note: In this case the report will include all the rare variants of the subject without any clinical interpretation, so will not be given any reference clinical & scientific literature, it will be up to the doctor who will be sent the report.'",
                            Duration = (byte)4,
                            Price = 100.0,
                            Title = "Esoma Clinico (WES) 100X"
                        },
                        new
                        {
                            Id = 2L,
                            Abbreviation = "WESR",
                            Description = "Comprehensive description of the sequencing methodology and pertinent gene coverage. In-depth analysis of rare causative variants documented in medical literature, emphasizing their pathogenic significance. Identification of infrequent variants prevalent in the general population (Minor Allele Frequency - MAF) < 1%. Definitive classification of significant variants based on globally recognized 'best practice' guidelines. Please note: The report will encompass all uncommon variants present in the individual, devoid of clinical interpretation. Subsequent evaluation based on clinical and scientific literature will be left to the healthcare professional receiving the report.",
                            Duration = (byte)5,
                            Price = 150.0,
                            Title = "Esoma Clinico (WES) 100X e relativa interpretazione clinica"
                        },
                        new
                        {
                            Id = 3L,
                            Abbreviation = "CGP",
                            Description = "Thorough elucidation of the genomic profiling methodology, encompassing a wide array of genes. Examination of somatic variants associated with cancer, including actionable mutations and potential therapeutic targets. Analysis of tumor mutational burden (TMB) and microsatellite instability (MSI) status. Comprehensive reporting of findings aligned with current clinical evidence and guidelines. Please Note: The provided report will furnish an extensive overview of genomic alterations without specific clinical correlations. Subsequent clinical interpretation is at the discretion of the healthcare provider.",
                            Duration = (byte)3,
                            Price = 250.0,
                            Title = "Comprehensive Genomic Profiling (CGP) 200X"
                        },
                        new
                        {
                            Id = 4L,
                            Abbreviation = "EMT",
                            Description = "A comprehensive overview of the exome mutation testing panel methodology, detailing the coverage of key genetic regions. Emphasis on identifying rare causative variants with significant clinical implications. Examination of low-frequency variants prevalent in the general population (Minor Allele Frequency - MAF) < 0.5%. Precise classification of identified variants following international 'best practice' guidelines. Please note: The report will encompass all rare variants identified in the individual without explicit clinical interpretation. Clinical and scientific referencing will be the responsibility of the healthcare professional receiving the report.",
                            Duration = (byte)5,
                            Price = 180.0,
                            Title = "Exome Mutation Testing (EMT) Panel"
                        },
                        new
                        {
                            Id = 5L,
                            Abbreviation = "PGX",
                            Description = "In-depth elucidation of the personalized genomic analysis panel methodology, encompassing key genetic markers. Focus on identifying genetic variants linked to drug metabolism and treatment response. Assessment of pharmacogenetic variants influencing medication efficacy and adverse reactions. Detailed reporting aligned with current clinical guidelines for personalized medicine. Note: The report provided will offer an extensive view of pharmacogenetic variants without specific clinical recommendations. Subsequent interpretation and medical decision-making rest with the healthcare provider.",
                            Duration = (byte)4,
                            Price = 120.0,
                            Title = "Personalized Genomic Analysis (PGX) Panel"
                        },
                        new
                        {
                            Id = 6L,
                            Abbreviation = "CEN",
                            Description = "Detailed overview of the Cardiovascular Exome Nexus (CEN) study methodology, covering a wide range of genes related to heart health. Identification of rare variants with potential implications for cardiovascular diseases. Analysis of low-frequency genetic variants with a focus on their impact on heart health (Minor Allele Frequency - MAF < 1%). Comprehensive classification of identified variants following established best practices. Please note: The report will encompass all rare variants found in the individual, without specific clinical interpretation. Clinical correlation and decision-making should be carried out by the healthcare professional receiving the report.",
                            Duration = (byte)1,
                            Price = 300.0,
                            Title = "Cardiovascular Exome Nexus (CEN) Study"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.TestResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long>("ClinicalProcessTestId")
                        .HasColumnType("bigint")
                        .HasColumnName("clinical_process_test_id");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<string>("DoctorNotes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("doctor_notes");

                    b.Property<string>("LabNotes")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("lab_notes");

                    b.Property<byte[]>("ReportAttachment")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("report_attachment");

                    b.Property<string>("ReportAttachmentTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("report_attachment_title");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("ClinicalProcessTestId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("testResult", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("address");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("avatar");

                    b.Property<int?>("ConsultationStatus")
                        .HasColumnType("int")
                        .HasColumnName("consultation_status");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on")
                        .HasDefaultValueSql("(getutcdate())");

                    b.Property<DateTimeOffset?>("DOB")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("dob");

                    b.Property<long?>("DoctorId")
                        .HasColumnType("bigint")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("ExpiryTime")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("expiry_time");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("first_name");

                    b.Property<byte?>("Gender")
                        .HasColumnType("tinyint")
                        .HasColumnName("gender");

                    b.Property<string>("Headline")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("headline");

                    b.Property<long?>("LabId")
                        .HasColumnType("bigint")
                        .HasColumnName("lab_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("last_name");

                    b.Property<string>("OTP")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("otp");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)")
                        .HasColumnName("phone_number");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint")
                        .HasColumnName("role");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1)
                        .HasColumnName("status");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DoctorId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Gender");

                    b.HasIndex("LabId");

                    b.HasIndex("Role");

                    b.HasIndex("Status");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.UserRefreshTokens", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_on");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("refresh_token");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<DateTimeOffset?>("UpdatedOn")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_on");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("userRefreshToken", (string)null);
                });

            modelBuilder.Entity("Entities.DataModels.UserRole", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("userRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "Doctor"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "Patient"
                        },
                        new
                        {
                            Id = (byte)3,
                            Title = "Lab"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.UserStatus", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint")
                        .HasColumnName("id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("userStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Title = "Active"
                        },
                        new
                        {
                            Id = (byte)2,
                            Title = "Inactive"
                        },
                        new
                        {
                            Id = (byte)3,
                            Title = "Deleted"
                        });
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalDetail", b =>
                {
                    b.HasOne("Entities.DataModels.User", "Users")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.ClinicalQuestion", "ClinicalQuestions")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ClinicalQuestions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalEnhancement", b =>
                {
                    b.HasOne("Entities.DataModels.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("Entities.DataModels.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalEnhancementAnswer", b =>
                {
                    b.HasOne("Entities.DataModels.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.ClinicalEnhancement", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalProcess", b =>
                {
                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Entities.DataModels.ClinicalProcessStatus", "NextStepClinicalProcess")
                        .WithMany()
                        .HasForeignKey("NextStep")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "Users")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.ClinicalProcessStatus", "ClinicalProcessStatuses")
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ClinicalProcessStatuses");

                    b.Navigation("CreatedByUser");

                    b.Navigation("NextStepClinicalProcess");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Entities.DataModels.ClinicalProcessTest", b =>
                {
                    b.HasOne("Entities.DataModels.ClinicalProcess", "ClinicalProcesses")
                        .WithMany()
                        .HasForeignKey("ClinicalProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Entities.DataModels.TestDetail", "TestDetails")
                        .WithMany()
                        .HasForeignKey("TestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("ClinicalProcesses");

                    b.Navigation("CreatedByUser");

                    b.Navigation("TestDetails");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Entities.DataModels.FAQ", b =>
                {
                    b.HasOne("Entities.DataModels.UserRole", "UserRoles")
                        .WithMany()
                        .HasForeignKey("ForWhom")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_FAQ_UserRoles");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Entities.DataModels.Notification", b =>
                {
                    b.HasOne("Entities.DataModels.User", "SendToUser")
                        .WithMany()
                        .HasForeignKey("SendTo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_SendToUser");

                    b.HasOne("Entities.DataModels.User", "SentByUser")
                        .WithMany()
                        .HasForeignKey("SentBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_SentByUser");

                    b.Navigation("SendToUser");

                    b.Navigation("SentByUser");
                });

            modelBuilder.Entity("Entities.DataModels.RequestMoreInfoQuestion", b =>
                {
                    b.HasOne("Entities.DataModels.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Entities.DataModels.SwipeActionSetting", b =>
                {
                    b.HasOne("Entities.DataModels.User", "user")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("FK_User_UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Entities.DataModels.TestResult", b =>
                {
                    b.HasOne("Entities.DataModels.ClinicalProcessTest", "ClinicalProcessTests")
                        .WithMany()
                        .HasForeignKey("ClinicalProcessTestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ClinicalProcessTests");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Entities.DataModels.User", b =>
                {
                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Entities.DataModels.User", "DoctorUsers")
                        .WithMany()
                        .HasForeignKey("DoctorId");

                    b.HasOne("Entities.DataModels.Gender", "Genders")
                        .WithMany()
                        .HasForeignKey("Gender");

                    b.HasOne("Entities.DataModels.User", "LabUsers")
                        .WithMany()
                        .HasForeignKey("LabId");

                    b.HasOne("Entities.DataModels.UserRole", "UserRoles")
                        .WithMany()
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.UserStatus", "UserStatuses")
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedByUser");

                    b.Navigation("DoctorUsers");

                    b.Navigation("Genders");

                    b.Navigation("LabUsers");

                    b.Navigation("UpdatedByUser");

                    b.Navigation("UserRoles");

                    b.Navigation("UserStatuses");
                });

            modelBuilder.Entity("Entities.DataModels.UserRefreshTokens", b =>
                {
                    b.HasOne("Entities.DataModels.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.HasOne("Entities.DataModels.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });
#pragma warning restore 612, 618
        }
    }
}
